spring:
    datasource:
        url: jdbc:mysql://pcshao.cn:9910/a66bbs?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=CTT
#        url: jdbc:mysql://127.0.0.1:3306/pcshao?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=CTT

        username: a66
        password: ghost666
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

    redis:
        # redis数据库索引（默认为0），我们使用索引为3的数据库，避免和其他数据库冲突
        database: 3
        # redis服务器地址（默认为localhost）
    #    host: localhost
#        host: 172.16.31.128
        host: 192.168.1.200
        # redis端口（默认为6379）
        port: 6379
        # redis访问密码（默认为空）
        password: 123456
        # redis连接超时时间（单位为毫秒）
        timeout: 5000
        # redis连接池配置
        pool:
        # 最大可用连接数（默认为8，负数表示无限）
        max-active: 8
        # 最大空闲连接数（默认为8，负数表示无限）
        max-idle: 8
        # 最小空闲连接数（默认为0，该值只有为正数才有作用）
        min-idle: 0
        # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
        max-wait: -1